from lib.commands import command, pm_command
from random import choice, randint


BASIC = (
	"Some things Man was never meant to know. For everything else, there's Google.",
	"Failure is not an option -- it comes bundled with Windows.",
	"Computer games don't affect kids; I mean if Pac-Man affected us as kids, we'd all be running around in darkened rooms, munching magic pills and listening to repetitive electronic music.",
	"COBOL programmers understand why women hate periods.",
	"Artificial Intelligence usually beats natural stupidity.",
	"To err is human... to really foul up requires the root password.",
	"Like car accidents, most hardware problems are due to driver error.",
	"If at first you don't succeed; call it version 1.0",
	"If Python is executable pseudocode, then perl is executable line noise.",
	"Programmers are tools for converting caffeine into code.",
	"Why do we want intelligent terminals when there are so many stupid users?",
	"I can't uninstall it, there seems to be some kind of 'Uninstall Shield'.",
	"See daddy ? All the keys are in alphabetical order now.",
	"Hey! It compiles! Ship it!",
	"SUPERCOMPUTER: what it sounded like before you bought it.",
	"Yo moma is like HTML: Tiny head, huge body.",
	"Windows Vista: It's like upgrading from Bill Clinton to George W. Bush.",
	"The more I C, the less I see.",
	"Life would be so much easier if we only had the source code.",
	"My software never has bugs. It just develops random features.",
	"The only problem with troubleshooting is that sometimes trouble shoots back.",
	"Crap... Someone knocked over my recycle bin... There's icons all over my desktop...",
	"Relax, its only ONES and ZEROS !",
	"rm -rf /bin/laden",
	"I don't care if you ARE getting a PhD in it ! Get away from that damn computer and go find a woman !",
	"The great thing about Object Oriented code is that it can make small, simple problems look like large, complex ones.",
	"If brute force doesn't solve your problems, then you aren't using enough.",
	"Programming is like sex, one mistake and you have to support it for the rest of your life.",
	"Unix is user-friendly. It's just very selective about who its friends are.",
	"Microsoft: \"You've got questions. We've got dancing paperclips.\"",
	"I'm not anti-social; I'm just not user friendly",
	"he world is coming to an end... SAVE YOUR BUFFERS !",
	"If you don't want to be replaced by a computer, don't act like one.",
	"Better to be a geek than an idiot.",
	"I went to a gentleman's cybercafe — and they offered me a 'laptop dance'.",
	"After Perl everything else is just assembly language.",
	"The Internet: where men are men, women are men, and children are FBI agents.",
	"There are 10 types of people in the world: those who understand binary, and those who don't.",
	"Difference between a virus and windows ? Viruses rarely fail.",
	"Hacking is like sex. You get in, you get out, and hope that you didn't leave something that can be traced back to you.",
	"1f u c4n r34d th1s u r34lly n33d t0 g37 l41d",
	"Helpdesk: There is an icon on your computer labeled \"My Computer\". Double click on it.\nUser: What's your computer doing on mine?",
	"I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.",
	"If debugging is the process of removing bugs, then programming must be the process of putting them in.",
	"Computer dating is fine, if you're a computer.",
	"Any fool can use a computer. Many do.",
	"Hardware: The parts of a computer system that can be kicked.",
	"Those who can't write programs, write help files.",
	"You know you're a geek when... You try to shoo a fly away from the monitor with your cursor. That just happened to me. It was scary.",
	"Computer language design is just like a stroll in the park. Jurassic Park, that is.",
)


PROGRAMMING = (
	("Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to build bigger and better idiots. So far, the universe is winning.", "Rick Cook"),
	("Lisp isn't a language, it's a building material.", "Alan Kay."),
	("Walking on water and developing software from a specification are easy if both are frozen.", "Edward V Berard"),
	("They don't make bugs like Bunny anymore.", "Olav Mjelde."),
	("A programming language is low level when its programs require attention to the irrelevant.", "Alan JPerlis."),
	("A C program is like a fast dance on a newly waxed dance floor by people carrying razors.", "Waldi Ravens."),
	("I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.", "Bjarne Stroustrup"),
	("Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter.", "Eric SRaymond"),
	("Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.", "Mosher’s Law of Software Engineering"),
	("I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.", "Oktal"),
	("Fine, Java MIGHT be a good example of what a programming language should be like. But Java applications are good examples of what applications SHOULDN’T be like.", "pixadel"),
	("Considering the current sad state of our computer programs, software development is clearly still a black art, and cannot yet be called an engineering discipline.", "Bill Clinton"),
	("The use of COBOL cripples the mind; its teaching should therefore be regarded as a criminal offense.", "E.WDijkstra"),
	("In the one and only true way. The object-oriented version of 'Spaghetti code' is, of course, 'Lasagna code'(Too many layers).", "Roberto Waltman."),
	("FORTRAN is not a flower but a weed — it is hardy, occasionally blooms, and grows in every computer.", "Alan JPerlis."),
	("For a long time it puzzled me how something so expensive, so leading edge, could be so useless. And then it occurred to me that a computer is a stupid machine with the ability to do incredibly smart things, while computer programmers are smart people with the ability to do incredibly stupid things. They are, in short, a perfect match.", "Bill Bryson"),
	("In My Egotistical Opinion, most people's C programs should be indented six feet downward and covered with dirt.", "Blair PHoughton."),
	("When someone says: 'I want a programming language in which I need only say what I wish done', give him a lollipop.", "Alan JPerlis"),
	("The evolution of languages: FORTRAN is a non-typed language. C is a weakly typed language. Ada is a strongly typed language. C++ is a strongly hyped language.", "Ron Sercely"),
	("Good design adds value faster than it adds cost.", "Thomas CGale"),
	("Python's a drop-in replacement for BASIC in the sense that Optimus Prime is a drop-in replacement for a truck.", "Cory Dodt"),
	("Talk is cheap. Show me the code.", "Linus Torvalds"),
	("Perfection [in design] is achieved, not when there is nothing more to add, but when there is nothing left to take away.", "Antoine de Saint-Exupéry"),
	("C is quirky, flawed, and an enormous success.", "Dennis MRitchie."),
	("In theory, theory and practice are the same. In practice, they’re not.", "Yoggi Berra"),
	("You can’t have great software without a great team, and most software teams behave like dysfunctional families.", "Jim McCarthy"),
	("PHP is a minor evil perpetrated and created by incompetent amateurs, whereas Perl is a great and insidious evil, perpetrated by skilled but perverted professionals.", "Jon Ribbens"),
	("Programming is like kicking yourself in the face, sooner or later your nose will bleed.", "Kyle Woodbury"),
	("Perl – The only language that looks the same before and after RSA encryption.", "Keith Bostic"),
	("It is easier to port a shell than a shell script.", "Larry Wall"),
	("I invented the term 'Object-Oriented', and I can tell you I did not have C++ in mind.", "Alan Kay"),
	("Learning to program has no more to do with designing interactive software than learning to touch type has to do with writing poetry", "Ted Nelson"),
	("The best programmers are not marginally better than merely good ones. They are an order-of-magnitude better, measured by whatever standard: conceptual creativity, speed, ingenuity of design, or problem-solving ability.", "Randall EStross"),
	("If McDonalds were run like a software company, one out of every hundred Big Macs would give you food poisoning, and the response would be, ‘We’re sorry, here’s a coupon for two more.’ ", "Mark Minasi"),
	("Beware of bugs in the above code; I have only proved it correct, not tried it.", "Donald EKnuth."),
	("Computer system analysis is like child-rearing; you can do grievous damage, but you cannot ensure success.", "Tom DeMarco"),
	("I don't care if it works on your machine! We are not shipping your machine!", "Vidiu Platon."),
	("Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.", "Christopher Thompson"),
	("Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", "Bill Gates"),
	("Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.", "Brian WKernighan."),
	("People think that computer science is the art of geniuses but the actual reality is the opposite, just many people doing things that build on each other, like a wall of mini stones.", "Donald Knuth"),
	("First learn computer science and all the theory. Next develop a programming style. Then forget all that and just hack.", "George Carrette"),
	("Most of you are familiar with the virtues of a programmer. There are three, of course: laziness, impatience, and hubris.", "Larry Wall"),
	("Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.", "Alan Kay"),
	("The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.", "Seymour Cray"),
	("To iterate is human, to recurse divine.", "LPeter Deutsch"),
	("On two occasions I have been asked [by members of Parliament]: 'Pray, MrBabbage, if you put into the machine wrong figures, will the right answers come out?' I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.", "Charles Babbage"),
	("Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.", "Linus Torvalds"),
	("Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.", "Martin Golding"),
	("There are two ways of constructing a software design. One way is to make it so simple that there are obviously no deficiencies. And the other way is to make it so complicated that there are no obvious deficiencies.", "C.A.RHoare"),
)


@command()
@pm_command()
def quote(param):
	if randint(0, 1):
		return " - ".join(choice(PROGRAMMING))
	else:
		return choice(BASIC)

